esphome:
  name: esp_led
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "DolenjcInStajerc"
  password: "stanovanje744"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    id: simple_led_light
    name: "Simple LED light"
    pin: D7